name: Python Build and Test Hello World
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
 
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # You can specify a version like '3.8', '3.9', etc.
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install -r requirements.txt  # Install dependencies from requirements.txt
 
    - name: Run tests with pytest
      run: |
        # Run pytest to discover and run tests
        # pytest --maxfail=1 --disable-warnings -q
         python hello.py
